version: '3.8'

services:
  web:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/usr/src/project/
    ports:
      - 8000:8000
    # Файл содержащий переменные для контейнера
    # env_file:
    #   - ./.env.dev
